all:
	javac -encoding UTF-8 Hello.java -classpath "../.."
	javac -encoding UTF-8 Frequencer.java -classpath "../.."
	javac -encoding UTF-8 InformationEstimator.java -classpath "../.."
	javac -encoding UTF-8 TestCase.java -classpath "../.."
run:
	java -classpath "../.." s4.B191850/Hello
	java -classpath "../.." s4.B191850/Frequencer
	java -classpath "../.." s4.B191850/InformationEstimator
	java -ea -classpath "../.." s4.B191850/TestCase
clean:
	rm -f *.class *~


